
const HOUSE_NAMES = ["โบสถ์เก่า", "สถานีวิทยุประจำเมือง", "หอเฝ้าระวังไฟ"];
 
const ITEM_LIBRARY = {
  portableradio: { name:"วิทยุพกพา", image:"#", category:"ไอเทมทั่วไป", desc:"วิทยุเครื่องเล็กใส่ถ่าน AA สองก้อน เมื่อเปิดฟังจะเจอแต่เสียงคลื่นซ่า", rare:false },
  oldnewspaper: { name:"หนังสือพิมพ์แมรี่ฮิลล์สฉบับเก่า", image:"#", category:"ไอเทมทั่วไป", desc:"หนังสือพิมพ์ฉบับเดือนก่อน หน้าคดีอาชญากรรมถูกตัดออกไป แต่ยังเห็นหัวข้อข่าวเล็กๆ", rare:false },
  vhstape: { name:"ม้วนเทป VHS ไร้ชื่อ", image:"#", category:"ไอเทมทั่วไป", desc:"ม้วนเทปวิดีโอสีดำที่ไม่มีป้ายชื่อ เขียนด้วยปากกาเคมีแค่นักเลข 1997-04-12", rare:false },
  expiredmilk: { name:"นมหมดอายุ", image:"#", category:"ไอเทมทั่วไป", desc:"สภาพไม่ดี รสชาติแย่ สภาพแย่กินก็ไม่ได้ แม้จะดูเหมือนว่าจะหมดอายุอีกหลายเดือนข้างหน้า แต่ข้างในเน่าไปแล้ว ข้างๆมีกระกาศตามหาคนหาย", rare:false },
  cassettetape: { name:"ตลับเทปเพลง", image:"#", category:"ไอเทมทั่วไป", desc:"ตลับเทปเพลงของศิลปินยุค 80s สภาพสายเทปหย่อนยาน ฟังแล้วเสียงยานเหมือนเสียงผีหลอก ไม่มีประโยชน์ในการเอาชีวิตรอด แต่เอาไว้ใส่เครื่อง Walkman เปิดฟังแก้เหงาได้", rare:false },
  goodwood: { name:"ไม้หน้าสามสภาพดี", image:"#", category:"ไอเทมประทังชีวิต", desc:"ไม้ท่อนหนาแข็งแรงที่ไร้รอยปลวก เหมาะสำหรับเอาไปตอกตรึงประตูหลักหรือหน้าต่าง ทอยเต๋าซ่อมบ้านสำเร็จได้ง่าย และบวกค่าทนทานบ้านสูง", rare:false },
  badwood: { name:"เศษไม้ผุปลวกกิน", image:"#", category:"ไอเทมประทังชีวิต", desc:"แผ่นไม้เก่าเปียกชื้นที่ถูกปลวกกินจนเป็นโพรงข้างใน", rare:false },
  Matchbox: { name:"เทียนไข + กล่องไม้ขีด", image:"#", category:"ไอเทมประทังชีวิต", desc:"เทียนไขเล่มหนาจากโบสถ์ประจำเมือง ใช้จุดให้แสงสว่างในช่วงที่ไฟดับ", rare:false },
  goodnailbox: { name:"กล่องตะปูไร้สนิม", image:"#", category:"ไอเทมประทังชีวิต", decs:"กล่องตะปูเหล็กกล้าแหลมคมพร้อมใช้งาน ใช้คู่กับแผ่นไม้เพื่อซ่อมบ้าน", rare:false },
  badnailbox: { name:"ตะปูสนิมเขร็ดคดงอ", image:"#", category:"ไอเทมประทังชีวิต", decs:"กำตะปูเก่าที่ทั้งขึ้นสนิมและดื้อคดงอ ใช้ตอกไม้ยากมาก", rare:false },
  bigcandle: { name:"เทียนเล่มหนา", image:"#", category:"ไอเทมประทังชีวิต", decs:"เทียนไขเนื้อดีเล่มใหญ่ จุดได้นานตลอดทั้งคืน ช่วยให้ห้องหลบภัยไม่มืดมิด ลดการสูญเสียสติของทุกคนในห้องได้ดีเยี่ยม", rare:false },
  smallcandle: { name:"เศษเทียนไขก้อนเล็ก", image:"#", category:"ไอเทมประทังชีวิต", decs:"เศษเทียนก้นกุฏิที่เหลือความยาวไม่ถึงนิ้ว จุดให้แสงสว่างได้แค่อึดใจเดียวก็ดับลง ไม่ค่อยช่วยคลายความกลัวในความมืดเท่าไหร่นัก", rare:false },
  goodlighter: { name:"ไฟแช็ก สภาพดี", image:"#", category:"ไอเทมประทังชีวิต", decs:"ไฟแช็กเหล็กทรงเก๋ยุค 90s จุดติดง่าย ลมพัดก็ไม่ดับง่ายๆ มีน้ำมันเต็มถัง พร้อมใช้จุดเทียน จุดเตา หรือใช้จุดไฟขู่สิ่งเหนือธรรมชาติในความมืด", rare:false },
  badlighter: { name:"ไฟแช็กพลาสติกไร้น้ำมัน", image:"#", category:"ไอเทมประทังชีวิต", decs:"ไฟแช็กพลาสติกราคาถูก กดแล้วมีแค่ประกายไฟแต่ไม่มีเปลวไฟออกมาเพราะน้ำมันหมด ต้องใช้ความพยายามสุ่มทอยเต๋าจุดหลายครั้งกว่าจะติดเศษเทียน", rare:false },
  cannedfood: { name:"สเต็กเนื้อกระป๋องเกรดดี", image:"#", category:"ไอเทมประทังชีวิต", decs:"เสบียงกระป๋องตราสมอ สภาพฝาไม่บวม ไม่ลอก ให้สารอาหารและความอิ่มสูง ช่วยฟื้นฟูค่าเสบียงกลางของบ้านได้เป็นอย่างมาก", rare:false },
  cannedtomato: { name:"ซุปมะเขือเทศกระป๋องบวมปูด", image:"#", category:"ไอเทมประทังชีวิต", decs:"กระป๋องอาหารที่มีอาการฝาบวมเต่งและมีกลิ่นเปรี้ยวเล็ดลอดออกมา แสดงถึงแบคทีเรียข้างใน ถ้าจวนตัวจนต้องกินแก้หิว จะต้องทอยเต๋าวัดดวงว่าท้องร่วงหรือไม่", rare:false },
  milkpowder: { name:"นมผง", image:"#", category:"ไอเทมประทังชีวิต", decs:"นมผงแบบชง สามารถชงดื่มเอาสารอาหารได้", rare:false },
  salinebottom: { name:"ขวดน้ำเกลือล้างแผลเข้มข้น", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ขวดน้ำเกลือจากอนามัย ใช้สาดใส่บาดแผลหรือผิวหนังของคนที่สงสัย หากเป็นมนุษย์จะแค่แสบแผล แต่ถ้าเป็นตัวปลอม ผิวหนังตรงนั้นจะเริ่มเกิดควันละลายสยดสยอง", rare:false },
  slivercross: { name:"ไม้กางเขนเงิน", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ไม้กางเขนทำจากเงินแท้ของโบสถ์ประจำเมือง", rare:false },
  axe: { name:"ขวานตัดไม้", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ขวานน้ำหนักเยอะ มีความคมและแรงส่งสูง ใช้สับทำลาย หรือใช้ฟันสู้กับน่ากลัวในระยะประชิดได้ดี", rare:false },
  holywater: { name:"ขวดน้ำมนต์ผ่านพิธี", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"น้ำมนต์ในขวดแก้วทรงโบราณ สาดใส่คนที่สงสัยหน้าประตูบ้าน", rare:false },
  crowbar: { name:"ชะแลงเหล็กกล้า", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ชะแลงสีแดงทรงขนานมาตรฐาน อุปกรณ์สารพัดประโยชน์", rare:false },
  saltbag: { name:"ถุงเกลือบริสุทธิ์", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ถุงผ้าโรยเกลือเม็ด  สามารถนำไปโรยเป็นแนวตามขอบหน้าต่างหรือประตูบ้าน เพื่อป้องกันไม่ให้วิญญาณหรือสิ่งเหนือธรรมชาติแอบเข้ามาในอาคาร", rare:false },
  stick: { name:"ไม้แหลม", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ท่อนไม้ที่เหลาจนปลายแหลมคม แม้จะดูเป็นอาวุธทำเองแบบงูๆ ปลาๆ แต่ถ้าจิ้มแทงเข้าจุดสำคัญของตัวสวมรอยในระยะประชิด ก็สามารถแทงถลอกหรือสร้างความเสียหายได้ดี", rare:false },
  garlic: { name:"พวงกระเทียมแห้งตากลม", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"พวงกระเทียมแห้งจากห้องครัว เอาไว้แขวนคอหรือเอาไว้ขู่", rare:false },
  torch: { name:"คบเพลิงผ้าชุบน้ำมันก๊าด", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ท่อนไม้พันผ้าหนาชุบน้ำมันก๊าด จุดไฟแล้วส่องสว่างได้ไกล", rare:false },
  fork: { name:"ส้อม", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ส้อมจิ้มเนื้อขนาดเล็กในห้องครัว เอาไว้ใช้เป็นอาวุธสู้ตายในยามจวนตัว", rare:false },
  shotgun: { name:"ปืนลูกซองแฝด", image:"#", category:"ไอเทมป้องกันตัวและอาวุธ", decs:"ปืนลูกซองล่าสัตว์ยิงแรงสูงมีอานุภาพทำลายล้างเป้าหมายในระยะประชิดกระเจิงทันที แต่กระสุนมีจำกัดมากเพียง 1 นัดเท่านั้น", rare:false },

  key: { name:"กุญแจ", image:"#", category:"ไอเทมทั่วไป", desc:"กุญแจดอกเก่าแก่ที่ถูกซ่อนไว้ใต้ลิ้นชักสถานีตำรวจ/อนามัย ใช้สำหรับเปิดประตูล็อคชั้นใต้ดินของโบสถ์", rare:true },
  polaroidcamera: { name:"กล้องโพลารอยด์ พร้อมฟิล์มเหลือ 2 รูป", image:"#", category:"ไอเทมทั่วไป", decs:"กล้องถ่ายรูปด่วนยุค 90s แฟลชสว่างวาบ เมื่อใช้ถ่ายคนที่สงสัย ภาพที่ออกมาทันทีจะแสดงให้เห็นว่าเงา หรือ ใบหน้าของคนๆ นั้นมีความบิดเบี้ยวผิดธรรมชาติหรือไม่", rare:true },
};
 
// พื้นที่สำรวจ —
const AREAS = [ 
  { id:"parking1", name:"เขตจอดรถสาธารณะของนักท่องเที่ยวเส้นบน", pool:["expiredmilk", "oldnewspaper", "cassettetape", "badlighter", "vhstape" ] },
  { id:"parking2", name:"เขตจอดรถสาธารณะของนักท่องเที่ยวเส้นล่าง", pool:["expiredmilk", "oldnewspaper", "cassettetape", "badlighter", "vhstape" ] },
  { id:"camp", name:"จุดตั้งแคมป์อุทยานและท่าเรือ", pool:["portableradio", "oldnewspaper", "expiredmilk", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "axe", "crowbar", "stick", "fork", ] },
  { id:"firelookout", name:"หอเฝ้าระวังไฟ เขตุ 2", pool:["portableradio", "polaroidcamera", "cassettetape", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "axe", "crowbar", "stick", "torch", "fork", ] },
  { id:"highschool", name:"โรงเรียนแมร์รี่ฮิลส์", pool:["polaroidcamera", "oldnewspaper", "vhstape", "expiredmilk", "cassettetape", "goodwood", "badwood", "goodnailbox", "badnailbox", "goodlighter", "badlighter", "crowbar", "stick", "fork", ] },
  { id:"newchurch", name:"โบสถ์ประจำเมือง", pool:["oldnewspaper", "expiredmilk", "goodwood", "badwood", "Matchbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "salinebottom", "slivercross", "holywater", "garlic", "saltbag", "torch", "fork", ] },
  { id:"districtoffice", name:"ที่ว่าการเมือง", pool:["portableradio", "oldnewspaper", "key", "cassettetape", "Matchbox", "goodlighter", "badlighter", "crowbar", "fork", "shotgun"] },
  { id:"newhealthcenter", name:"อนามัยประจำเมือง", pool:["oldnewspaper", "Matchbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "fork", ] },
  { id:"market", name:"ตลาดพืช", pool:["oldnewspaper", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "cannedfood", "cannedtomato", "milkpowder", "axe", "saltbag","stick", "garlic", "torch", ] },
  { id:"newpolicestation", name:"สำนักงานตำรวจ", pool:["portableradio", "oldnewspaper", "cassettetape", "Matchbox", "goodlighter", "badlighter", "axe", "crowbar", "stick", "fork", "shotgun"] },
  { id:"gasstation", name:"ปั้มน้ำมัน", pool:["oldnewspaper", "expiredmilk", "cassettetape", "goodnailbox", "badnailbox", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "crowbar", "stick", ] },
  { id:"newtomb", name:"สุสานใหม่", pool:["oldnewspaper", "vhstape", "smallcandle", "badlighter", "slivercross", "stick", "torch", ] },
  { id:"downtown", name:"ย่านการค้า ดาวน์-ทาวน์", pool:["oldnewspaper", "expiredmilk", "cassettetape", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "milkpowder", "saltbag", "garlic", "fork", ] },
  { id:"uptown", name:"ย่านที่อยู่อาศัย อัป-ทาวน์", pool:["oldnewspaper", "vhstape", "expiredmilk", "cassettetape", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "milkpowder", "axe", "crowbar", "saltbag", "stick", "garlic", "torch", "fork"] },
  { id:"maple", name:"ย่านที่อยู่อาศัย เมเปิ้ล", pool:["oldnewspaper", "vhstape", "expiredmilk", "cassettetape", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "milkpowder", "slivercross", "saltbag", "stick", "garlic", "fork"] },
  { id:"store", name:"ร้านค้าของชำ", pool:["oldnewspaper", "expiredmilk", "Matchbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "milkpowder", "saltbag", "garlic", ] },
  { id:"hospital", name:"โรงพยาบาลเก่า", pool:["oldnewspaper", "Matchbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "fork" ] },
  { id:"oldpolicestation", name:"สถานีตำรวจเก่า", pool:["portableradio", "oldnewspaper", "cassettetape", "Matchbox", "goodlighter", "badlighter","axe", "crowbar", "stick", "shotgun"] },
  { id:"school", name:"โรงเรียนประถมประจำเมือง", pool:["oldnewspaper", "vhstape", "expiredmilk", "cassettetape", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "goodlighter", "badlighter", "milkpowder", "crowbar", "fork"] },
  { id:"oldtomb", name:"สุสานเก่า", pool:["oldnewspaper", "vhstape", "smallcandle", "badlighter", "slivercross", "torch"] },
  { id:"hometown", name:"ย่านที่อยู่อาศัย เซาธ์-เมเปิ้ล", pool:["polaroidcamera", "oldnewspaper", "vhstape", "expiredmilk", "cassettetape", "goodwood", "badwood", "Matchbox", "goodnailbox", "badnailbox", "bigcandle", "smallcandle", "goodlighter", "badlighter", "cannedfood", "cannedtomato", "milkpowder", "slivercross", "saltbag","stick", "garlic", "torch", "fork"] }
];