//  Map Start
const MAPS = [
    {
        id: "Marry_Hills",
        label: "Marry Hills",
        image: "image/Map/Marry_hills_map.png",
        locations: [
            {
                id:"newtown",
                name: "เมืองใหม่",
                x:58.56,
                y:16,
                image:"#",
                description: "เมืองที่ถูกสร้างขึ้นมาใหม่ บลา บลา บลา",
            },
            {
                id:"oldtown",
                name:"เมืองเก่า",
                x:96,
                y:58.5,
                image:"#",
                description:"เมืองเก่าที่อยู่มานานกว่า บลา บลา บลา",
            },
            {
                id:"parking1",
                name:"เขตุจอดรถสาธารณะของนักท่องเที่ยวเส้นบน",
                x:43,
                y:25,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"parking2",
                name:"เขตุจอดรถสาธารณะของนักท่องเที่ยวเส้นล่าง",
                x:60.7,
                y:57.4,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"radiostation",
                name:"สถานีวิทยุประจำเมือง",
                x:32.2,
                y:9.9,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"firelookout1",
                name:"หอเฝ้าระวังไฟ เขตุ 1",
                x:52.4,
                y:61.2,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"camp",
                name:"จุดตั้งแคมป์อุทยานและท่าเรือ",
                x:20.7,
                y:38.7,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"firelookout2",
                name:"หอเฝ้าระวังไฟ เขตุ 2",
                x:3.1,
                y:72.8,
                image:"#",
                description:"บลา บลา บลา",
            }
        ]
    },
    {
        id: "North_Marry_Hills",
        label: "North Marry Hills",
        image: "image/Map/North_marry_hills_map.png",
        locations: [
            {
                id:"highschool",
                name:"โรงเรียน Marry Hills",
                x:15.9,
                y:20.4,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"newchurch",
                name:"โบสถ์ประจำเมือง",
                x:69.1,
                y:16.1,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"districtoffice",
                name:"ที่ว่าการอำเภอ",
                x:43.3,
                y:44,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"newhealthcenter",
                name:"อนามัยประจำเมือง",
                x:26.2,
                y:68.8,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"market",
                name:"ตลาดพืช",
                x:57.5,
                y:73.8,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"newpolicestation",
                name:"สำนักงานตำรวจ",
                x:72.2,
                y:73,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"gasstation",
                name:"ปั้มน้ำมัน",
                x:17.3,
                y:92.8,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"newtomb",
                name:"สุสาน",
                x:84,
                y:11.1,
                image:"#",
                description:"บลา บลา บลา",
            },
        ]
    },
    {
        id:"South_Marry_Hills",
        label:"South Marry Hills",
        image:"image/Map/South_marry_hills_map.png",
        locations: [
            {
                id:"oldchurch",
                name:"โบสถ์เก่า",
                x:81.4,
                y:25.4,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"store",
                name:"ร้านค้าของชำ",
                x:80.7,
                y:51.3,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"hospital",
                name:"โรงพยาบาลเก่า",
                x:79.8,
                y:71.3,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"oldpolicestation",
                name:"สถานีตำรวจเก่า",
                x:51.1,
                y:74.5,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"school",
                name:"โรงเรียนประถมประจำเมือง",
                x:29.6,
                y:79.1,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"oldtomb",
                name:"สุสาน",
                x:95.3,
                y:22.5,
                image:"#",
                description:"บลา บลา บลา",
            },
            {
                id:"hometown",
                name:"เขตุที่อยู่อาศัย",
                x:45.2,
                y:32.2,
                image:"#",
                description:"บลา บลา บลา",
            }
        ]
    }
];
